spring:
  datasource:
    url: jdbc:h2:mem:ib;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  messages:
    basename: message

server:
  servlet:
    context-path: /imdb



#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/imdb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: imdb
#    password: password
#    name: imdb
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.
#    show-sql: true
#  messages:
#    basename: message

#    spring:
#      data:
#        mongodb:
#          host: localhost
#          uri: mongodb://localhost:27017
#          port: 27017
#          database: imdb
#      jpa:
#        show-sql: true